version: '3'

services:
    website:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./website:/website
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DB_HOST=db
            - DB_NAME=website
            - DB_USER=postgres
            - DB_PASS=postgres
        depends_on: 
            - db

    db:
        image: postgres:12-alpine
        environment: 
            - POSTGRES_DB=website
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
