# Generated by Django 3.0.4 on 2020-04-16 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200415_1218'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
