# Generated by Django 3.0.4 on 2020-04-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='booking_type',
            field=models.IntegerField(choices=[(1, 'Online Booking'), (2, 'Offline Booking')]),
        ),
    ]
