# Generated by Django 3.0.4 on 2020-05-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipments', '0010_auto_20200430_2002'),
        ('bookings', '0009_auto_20200511_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_ordered', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('items', models.ManyToManyField(to='bookings.EnquiryItem')),
            ],
        ),
    ]
