# Generated by Django 3.0.4 on 2020-05-30 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auto_20200530_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquirycart',
            old_name='date_ordered',
            new_name='enquiry_date',
        ),
    ]
