# Generated by Django 3.0.4 on 2020-03-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={},
        ),
        migrations.AlterModelOptions(
            name='equipments',
            options={'verbose_name': 'Equipments', 'verbose_name_plural': 'Equipments'},
        ),
        migrations.RenameField(
            model_name='accessories',
            old_name='model',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='model',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='lens',
            old_name='model',
            new_name='model_name',
        ),
    ]
