# Generated by Django 3.0.4 on 2020-03-21 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20200321_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Camera', 'verbose_name_plural': 'Cameras'},
        ),
    ]
