# Generated by Django 3.0.4 on 2020-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_auto_20200321_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('Camera', 'Camera'), ('Lens', 'Lens'), ('Accessories', 'Accessories')], max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('inventory', models.IntegerField()),
                ('ratings', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
            },
        ),
    ]
