# Generated by Django 3.0.4 on 2020-04-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_auto_20200417_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipments',
            options={'verbose_name': 'Equipment_images', 'verbose_name_plural': 'Equipment_images'},
        ),
    ]
