# Generated by Django 3.0.4 on 2020-04-26 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_auto_20200426_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='media/equipments')),
            ],
            options={
                'verbose_name': 'Equipment_images',
                'verbose_name_plural': 'Equipment_images',
            },
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='accessories_key',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='camera_key',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='lens_key',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='inventory',
            new_name='count',
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
        migrations.DeleteModel(
            name='Equipments',
        ),
        migrations.DeleteModel(
            name='Lens',
        ),
        migrations.AddField(
            model_name='equipment_images',
            name='equipment_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.Equipment'),
        ),
    ]
