# Generated by Django 3.0.4 on 2020-04-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0007_auto_20200426_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='media/equipments'),
        ),
        migrations.DeleteModel(
            name='Equipment_Images',
        ),
    ]
