# Generated by Django 3.0.4 on 2020-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0008_auto_20200427_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=700.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='equipments'),
        ),
    ]
