# Generated by Django 3.0.4 on 2020-04-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_auto_20200429_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cost/day'),
        ),
    ]
