# Generated by Django 3.0.4 on 2020-06-22 09:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0010_auto_20200430_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
                ('request', models.TextField()),
                ('response', models.TextField()),
                ('status_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure')], max_length=20)),
            ],
            options={
                'verbose_name': 'Api log',
                'verbose_name_plural': 'Api logs',
            },
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=550),
        ),
    ]
