# Generated by Django 3.0.4 on 2020-06-22 09:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0011_auto_20200622_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=350),
        ),
    ]
