# Generated by Django 3.0.4 on 2020-03-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200328_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.CharField(blank=True, choices=[('RC book', 'RC book'), ('Passport', 'Passport'), ('Driving licence', 'Driving licence'), ('Aadhaar card', 'Aadhaar card'), ('Pan card', 'Pan card')], max_length=20, null=True, verbose_name='Id proof'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_proof_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Id Proof number'),
        ),
    ]
